### ISSUE TITLE
Kind Request to Include Our Paper in Your Paper List

### ISSUE THREAD

**Issue by Furyton** [RUC-NLPIR/GenIR-Survey#1]
Hi there,

I wanted to express my admiration for the comprehensive survey and paper list you've compiled. It's an invaluable asset for the community.

I'm reaching out to kindly draw your attention to our recent publication at SIGIR'24 titled "Generative Retrieval as Multi-Vector Dense Retrieval." We've explored the theoretical relationship between generative-style (Generative Retrieval) and matching-style (Multi-Vector Dense Retrieval) scoring in information retrieval, and we hope to offer fresh insights into the topic.

The paper is available on arXiv at [this link](https://arxiv.org/abs/2404.00684), and the associated codebase is hosted on [GitHub](https://github.com/Furyton/GR-as-MVDR). Below, I've included the abstract for your convenience.

Would you be open to considering the addition of our paper to your repository? We believe it could make a meaningful contribution.

Thanks so much for your consideration.

Best regards,
Shiguang Wu

---

Abstract

> Generative retrieval generates identifiers of relevant documents in an end-to-end manner using a sequence-to-sequence architecture for a given query. The relation between generative retrieval and other retrieval methods, especially those based on matching within dense retrieval models, is not yet fully comprehended. Prior work has demonstrated that generative retrieval with atomic identifiers is equivalent to single-vector dense retrieval. Accordingly, generative retrieval exhibits behavior analogous to hierarchical search within a tree index in dense retrieval when using hierarchical semantic identifiers. However, prior work focuses solely on the retrieval stage without considering the deep interactions within the decoder of generative retrieval.
> 
> In this paper, we fill this gap by demonstrating that generative retrieval and multi-vector dense retrieval share the same framework for measuring the relevance to a query of a document. Specifically, we examine the attention layer and prediction head of generative retrieval, revealing that generative retrieval can be understood as a special case of multi-vector dense retrieval. Both methods compute relevance as a sum of products of query and document vectors and an alignment matrix. We then explore how generative retrieval applies this framework, employing distinct strategies for computing document token vectors and the alignment matrix. We have conducted experiments to verify our conclusions and show that both paradigms exhibit commonalities of term matching in their alignment matrix.
> 
> Our finding applies to many generative retrieval identifier designs and provides possible explanations on how generative retrieval can express query-document relevance. As multi-vector dense retrieval is the state-of-the-art dense retrieval method currently, understanding the connection between generative retrieval and multi-vector dense retrieval is crucial for shedding light on the underlying mechanisms of generative retrieval and for developing, and understanding the potential of, new retrieval models.

**Comment by sunnynexus** [comment]
Thank you for reaching out and sharing your publication, "Generative Retrieval as Multi-Vector Dense Retrieval," presented at SIGIR'24. Your exploration of the relationship between generative and matching-based scoring mechanisms in information retrieval to be both insightful and significant.

We have already added your paper to the 'Analysis' section of my GitHub paper list. Additionally, I am more than willing to include it in future updates of the paper version.

Best regards,
Xiaoxi Li

**Comment by Furyton** [comment]
Thank you very much for your prompt response and consideration. I will close this issue :)

Shiguang
